name: CI/CD Pipeline for Backend and Frontend

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write #

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}/backend
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Tag Docker Image
        run: |
          docker build -f backend/Dockerfile -t $IMAGE_NAME:$COMMIT_SHA ./backend
          docker tag $IMAGE_NAME:$COMMIT_SHA $IMAGE_NAME:latest  # Also tag as latest

      - name: Push Docker Image to GHCR
        run: |
          docker push $IMAGE_NAME:$COMMIT_SHA  # Push commit-specific tag
          docker push $IMAGE_NAME:latest       # Push latest tag

      - name: Install Railway CLI
        run: |
          curl -fsSL https://railway.app/install.sh | sh
          export PATH="$HOME/.railway/bin:$PATH"

      - name: 🚀 Trigger Railway Deployment
        run: railway up --service=${{ env.SVC_ID }} --detach
