name: CI/CD Pipeline for Backend on Main Branch

on:
  push:
    branches:
      - main

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-backend:
    runs-on: ubuntu-latest
    env:
      COMMIT_SHA: ${{ github.sha }}
      IMAGE_NAME: ghcr.io/${{ github.repository }}/backend
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry (GHCR)
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push Docker Image to GHCR
        run: |
          docker build -f backend/Dockerfile -t $IMAGE_NAME:${{ github.sha }} ./backend
          docker push $IMAGE_NAME:${{ github.sha }}

  deploy-backend:
    needs: build-and-push-backend
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_PROJECT_ID: ${{ secrets.RAILWAY_PROJECT_ID }}
      RAILWAY_SERVICE_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
    steps:
      - uses: actions/checkout@v3
      - name: Print Docker Image Tag
        run: |
          echo "Deploying $IMAGE_NAME:${{ github.sha }} to Railway"
      - name: Deploy Backend to Railway
        run: |
          railway redeploy -y --service $RAILWAY_SERVICE_ID
