name: CI/CD Pipeline for Backend and Frontend on Pull Request

on:
  pull_request:
    branches:
      - "*"

jobs:
  build-backend_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout backend code
        uses: actions/checkout@v2
      - name: Set up Docker for backend
        run: |
          docker build -t passwordless-backend .
      - name: Run backend tests
        run: |
          docker run passwordless-backend npm test
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Comment on PR if tests pass
        if: success()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Tests passed successfully! 🎉"

  build-frontend_and_run_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout frontend code
        uses: actions/checkout@v2
      - name: Set up Docker for frontend
        run: |
          docker build -t passwordless-frontend .
      - name: Run frontend tests
        run: |
          docker run passwordless-frontend npm test
      - name: Install GitHub CLI
        run: sudo apt-get install gh
      - name: Comment on PR if tests pass
        if: success()
        run: |
          gh pr comment ${{ github.event.pull_request.number }} --body "Frontend tests passed successfully! 🎉"
